name: GITOPENCLAW-WORKFLOW-AGENT

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  actions: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: >-
      (github.event_name == 'issues')
      || (github.event_name == 'issue_comment' && github.event.comment.user.login != 'github-actions[bot]')
    steps:
      - name: Authorize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PERM=$(gh api "repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission" --jq '.permission' 2>/dev/null || echo "none")
          echo "Actor: ${{ github.actor }}, Permission: $PERM"
          if [[ "$PERM" != "admin" && "$PERM" != "maintain" && "$PERM" != "write" ]]; then
            echo "::error::Unauthorized: ${{ github.actor }} has '$PERM' permission"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Guard
        run: bun .GITOPENCLAW/lifecycle/GITOPENCLAW-ENABLED.ts

      - name: Preinstall
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun .GITOPENCLAW/lifecycle/GITOPENCLAW-INDICATOR.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install .GITOPENCLAW dependencies
        run: cd .GITOPENCLAW && bun install

      - name: Run
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun .GITOPENCLAW/lifecycle/GITOPENCLAW-AGENT.ts
